Research Showcase plots
========================================================

```{r}
require("data.table")
require("ggplot2")
require("wordcloud")
require(RColorBrewer)
```

## Archetypes
What films reccur often?

First, films we see in the X meets Y pattern:

```{r}
films <-fread(input="../searches/x_meets_y_word-counts.txt", skip=8)
# Split into two clouds of 50 words
setA = 1:50*2#2*1:(nrow(films)/2)
setB = 1:50*2-1#2*1:(nrow(films)/2)-1
png("wordcloud1.png", width=12,height=8, units='in', res=300)
wordcloud(films[setA,film], films[setA,count], scale=c(3.6,.1), random.order=FALSE, rot.per=.15, colors=brewer.pal(8,"Oranges")[2:7])
dev.off()
png("wordcloud2.png", width=12,height=8, units='in', res=300)
wordcloud(films[setB,film], films[setB,count], scale=c(3.6,.1), random.order=FALSE, rot.per=.15, colors=brewer.pal(8,"Blues")[2:7])
dev.off()


```

An {X} twist
```{r}
films <-fread(input="../searches/a_X_twist-counts.txt")
films[, twist:=gsub("a | twist", "", twist)]
ggplot(films[1:10], aes(x=factor(c("Twists")), y=count, fill=twist))+ scale_fill_hue(h=c(180, 270))+geom_bar(stat="identity")+theme_minimal()+ geom_text(aes(label = twist, size = count), hjust = 0.5, vjust = 3, position = "stack")+ scale_size(range=c(3,6))
```

```{r fig.width=7, fig.height=6}
ggplot(films[1:20], aes(y=count, x=factor(twist, levels=twist, ordered=TRUE)))+geom_bar()+theme_minimal()+coord_flip()+labs(x="twist")

```

-Esque phrase
```{r}
phrases <-fread(input="searches/esque-sentences-counts.txt")
png("wordcloud3.png", width=12,height=8, units='in', res=300)
wordcloud(phrases[,phrase], films[,count], scale=c(3.6,.1), random.order=FALSE, rot.per=.15, colors=brewer.pal(8,"Greys")[2:7])
dev.off()
```

## Example: Super 8
How often are other films discussed in reviews about Super 8?

```{r}
films <- fread(input="examples/stats/super8-film-counts.csv")
ggplot(films[total.matches > 5], aes(x=factor(movie), y=total.matches))+geom_bar(stat="identity")+theme_minimal()
```

You can also embed plots, for example:

```{r fig.width=7, fig.height=6}
plot(cars)
```

